### ISSUE TITLE
Deploy bot on cloud

### ISSUE THREAD

**Issue by tiazahmd** [PifagorRZ/voting_bot#7]
Deploy bot on either Heroku or Digital Ocean.

**Comment by nonbeing** [comment]
Anattaguy here. I have some suggestions and ideas related to this. They're in today's (Jun 18) chat history of the #voting-bot channel:

> I think what we would like is a deployment system so that whenever @Evhenii  or the "push master" merges a branch into master (which is effectively the production or golden branch to which only the push master has push-rights to), then using GitHub's post-receive webhook, we have the master branch auto-deployed to the remote server (e.g. the GCP VM)


>So any pushes or PRs that are merged to master from GH or otherwise,  go live immediately and automatically.


> We will also need a roll-back system to easily revert a bad push and restore to a good state.

~I've started on this, so assigning to myself.~ @PifagorRZ could you add me as collaborator so that I can assign this issue to myself, and also contribute to the bot code itself?

**Comment by nonbeing** [comment]
Completed with commit 548be1735e31ae35cc5d842503052b7abda43b0d
